[LINEMODE]

Chips = 0;  ; 0 - both, 1 - chip 1 only, 2 - chip 2 only

[WAKEUP]

WakeUpOnAllMsg = 1     ; 0 - Wakeup from NMBusSleep only by NM messages
                       ; 1 - wakeup from NMBusSleep by any message


[MESSAGE]

DlcLen = 8             ; length of NM message in bytes (minimum 2, maximum 8 (CAN) or 64 (CAN FD))
RingDataStartIndex = 2 ; minimum 2
RingDataLength = 6     ; length of ring data in bytes
RingDataFill = 0

NM_MESSAGE_FDF = 0     ; 0 - NM message is sent as classic CAN message
                       ; 1 - in case of a CAN FD network, the NM message is sent with FDF = 1

NM_MESSAGE_BRS = 0     ; 0 - NM message is sent with BRS = 0
                       ; 1 - in case of a CAN FD network and in case that FDF = 1, the NM message is sent with BRS = 1


[WRITE]

VERBOSE = 1  ; verbose level
             ; 0 - no messages
             ; 1 - some messages
             ; 2 - more messages
             ; 3 - even more messages

[NAMES]

CALLBACKFunc1 = apBusSleep
CALLBACKFunc2 = apCanSleep
CALLBACKFunc3 = apCanNormal
CALLBACKFunc4 = apCanWakeUp
CALLBACKFunc5 = apCanOff
CALLBACKFunc6 = apCanOn
CALLBACKFunc7 = apIndRingData

[TIMER]

; all timers are given in milliseconds
T_RING_TYP    = 100   ; typical time interval between two ring messages
T_RING_MAX    = 250   ; maximum time interval between two ring
T_NOTLAUF     = 1000  ; time interval between two ring messages with NMLimpHome identification
T_BUSSLEEP    = 1500  ; time the NM waits before transition into the state NMBusSleep