"""
Tests for GM_VIP_Automation_Framework.core.symbol_discovery
============================================================
All Trace32 API calls are mocked – no hardware required.
"""

import sys
import unittest
from unittest.mock import MagicMock, call, patch

# ---------------------------------------------------------------------------
# Stub out lauterbach.trace32.rcl (mirrors test_core.py setup)
# ---------------------------------------------------------------------------
_pyrcl_mock = MagicMock()
sys.modules.setdefault("lauterbach", MagicMock())
sys.modules.setdefault("lauterbach.trace32", MagicMock())
sys.modules.setdefault("lauterbach.trace32.rcl", _pyrcl_mock)
sys.modules.setdefault("lauterbach.trace32.rcl._rc", MagicMock())
sys.modules.setdefault("lauterbach.trace32.rcl._rc._error", MagicMock())


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SAMPLE_SYMBOL_LIST = """\
; Symbol list generated by SYMBOL.LIST *
\\src\\main.c\\main         0x80001000 0x40 CODE
\\src\\main.c\\g_counter    0x80004000 0x04 DATA
\\src\\main.c\\helperFunc   0x80001040 0x20 CODE
\\src\\utils.c\\utilFunc    0x80002000 0x30 CODE
\\src\\utils.c\\g_flag      0x80005000 0x01 DATA
flatFunction               0x80003000 0x10 CODE
G_GLOBAL_VAR               0x80006000 0x04 DATA
"""

_SAMPLE_NO_TYPE = """\
; Symbol list (stripped binary – no type column)
main         0x80001000
g_counter    0x80004000
helperFunc   0x80001040
"""


def _make_conn(area_text: str = _SAMPLE_SYMBOL_LIST):
    """Return a mock T32Connection that simulates SYMBOL.LIST output."""
    conn = MagicMock()
    conn.is_connected.return_value = True

    # AREA.SAVE writes a temp file; we simulate by writing text ourselves.
    _saved_tmp = {}

    def _cmd(c):
        if c.startswith("AREA.SAVE"):
            tmp_path = c.split(None, 1)[1].strip()
            import pathlib
            pathlib.Path(tmp_path).write_text(area_text, encoding="utf-8")
            _saved_tmp["path"] = tmp_path
        # All other commands are no-ops.

    def _fnc(expr):
        if "SYMBOL.EXIST" in expr:
            # Symbols that contain "missing" do not exist.
            return "FALSE()" if "missing" in expr.lower() else "TRUE()"
        if "ADDRESS.OFFSET" in expr:
            return "0x80001234"
        return "0"

    conn.cmd.side_effect = _cmd
    conn.fnc.side_effect = _fnc
    return conn


# ---------------------------------------------------------------------------
# SymbolKind
# ---------------------------------------------------------------------------

class TestSymbolKind(unittest.TestCase):

    def test_values(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import SymbolKind
        self.assertEqual(SymbolKind.FUNCTION.value, "FUNCTION")
        self.assertEqual(SymbolKind.VARIABLE.value, "VARIABLE")
        self.assertEqual(SymbolKind.MODULE.value,   "MODULE")
        self.assertEqual(SymbolKind.UNKNOWN.value,  "UNKNOWN")


# ---------------------------------------------------------------------------
# DiscoveredSymbol
# ---------------------------------------------------------------------------

class TestDiscoveredSymbol(unittest.TestCase):

    def test_to_dict(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import (
            DiscoveredSymbol, SymbolKind,
        )
        sym = DiscoveredSymbol(
            name="\\src\\main.c\\myFunc",
            short_name="myFunc",
            module="src\\main.c",
            kind=SymbolKind.FUNCTION,
            address="0x80001000",
            size=64,
            exists=True,
        )
        d = sym.to_dict()
        self.assertEqual(d["name"],       "\\src\\main.c\\myFunc")
        self.assertEqual(d["short_name"], "myFunc")
        self.assertEqual(d["module"],     "src\\main.c")
        self.assertEqual(d["kind"],       "FUNCTION")
        self.assertEqual(d["address"],    "0x80001000")
        self.assertEqual(d["size"],       64)
        self.assertTrue(d["exists"])

    def test_frozen(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import (
            DiscoveredSymbol,
        )
        sym = DiscoveredSymbol(name="myFunc")
        with self.assertRaises(Exception):
            sym.name = "other"  # type: ignore[misc]


# ---------------------------------------------------------------------------
# _parse_symbol_list  (unit tests for the parser directly)
# ---------------------------------------------------------------------------

class TestParseSymbolList(unittest.TestCase):

    def setUp(self):
        from GM_VIP_Automation_Framework.core import symbol_discovery as sd
        self.sd = sd

    def test_module_qualified_function(self):
        parsed = self.sd._parse_symbol_list(_SAMPLE_SYMBOL_LIST)
        names = [s.short_name for s in parsed]
        self.assertIn("main", names)
        self.assertIn("helperFunc", names)

    def test_module_qualified_variable(self):
        parsed = self.sd._parse_symbol_list(_SAMPLE_SYMBOL_LIST)
        vars_ = [s for s in parsed if s.kind == self.sd.SymbolKind.VARIABLE]
        var_names = [s.short_name for s in vars_]
        self.assertIn("g_counter", var_names)
        self.assertIn("g_flag", var_names)

    def test_module_extraction(self):
        parsed = self.sd._parse_symbol_list(_SAMPLE_SYMBOL_LIST)
        main_sym = next(s for s in parsed if s.short_name == "main")
        self.assertIn("main.c", main_sym.module)

    def test_flat_symbol_has_empty_module(self):
        parsed = self.sd._parse_symbol_list(_SAMPLE_SYMBOL_LIST)
        flat = next(s for s in parsed if s.short_name == "flatFunction")
        self.assertEqual(flat.module, "")

    def test_no_type_column_heuristic(self):
        """When no section-kind column is present the name heuristic kicks in."""
        parsed = self.sd._parse_symbol_list(_SAMPLE_NO_TYPE)
        by_name = {s.short_name: s for s in parsed}
        # g_counter starts with g_ → VARIABLE heuristic
        self.assertEqual(by_name["g_counter"].kind, self.sd.SymbolKind.VARIABLE)
        # main → FUNCTION heuristic (default)
        self.assertEqual(by_name["main"].kind, self.sd.SymbolKind.FUNCTION)

    def test_global_caps_variable_heuristic(self):
        parsed = self.sd._parse_symbol_list(_SAMPLE_SYMBOL_LIST)
        by_name = {s.short_name: s for s in parsed}
        self.assertEqual(by_name["G_GLOBAL_VAR"].kind, self.sd.SymbolKind.VARIABLE)

    def test_duplicate_symbols_skipped(self):
        doubled = _SAMPLE_SYMBOL_LIST + _SAMPLE_SYMBOL_LIST
        parsed = self.sd._parse_symbol_list(doubled)
        names = [s.short_name for s in parsed]
        self.assertEqual(len(names), len(set(names)))

    def test_comment_lines_ignored(self):
        text = "; this is a comment\n// another comment\n"
        parsed = self.sd._parse_symbol_list(text)
        self.assertEqual(parsed, [])

    def test_empty_input(self):
        parsed = self.sd._parse_symbol_list("")
        self.assertEqual(parsed, [])


# ---------------------------------------------------------------------------
# SymbolInventory
# ---------------------------------------------------------------------------

class TestSymbolInventory(unittest.TestCase):

    def _make_inventory(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import (
            DiscoveredSymbol, SymbolInventory, SymbolKind,
        )
        syms = [
            DiscoveredSymbol("\\a.c\\funcA", "funcA", "a.c", SymbolKind.FUNCTION, "0x100", 0x20),
            DiscoveredSymbol("\\a.c\\varA",  "varA",  "a.c", SymbolKind.VARIABLE, "0x200", 0x04),
            DiscoveredSymbol("\\b.c\\funcB", "funcB", "b.c", SymbolKind.FUNCTION, "0x300", 0x10),
        ]
        return SymbolInventory(syms)

    def test_modules(self):
        inv = self._make_inventory()
        self.assertIn("a.c", inv.modules)
        self.assertIn("b.c", inv.modules)

    def test_functions(self):
        inv = self._make_inventory()
        self.assertEqual(len(inv.functions), 2)

    def test_variables(self):
        inv = self._make_inventory()
        self.assertEqual(len(inv.variables), 1)

    def test_functions_in(self):
        inv = self._make_inventory()
        self.assertEqual(len(inv.functions_in("a.c")), 1)
        self.assertEqual(inv.functions_in("a.c")[0].short_name, "funcA")

    def test_variables_in(self):
        inv = self._make_inventory()
        self.assertEqual(len(inv.variables_in("a.c")), 1)

    def test_len(self):
        inv = self._make_inventory()
        self.assertEqual(len(inv), 3)

    def test_iter(self):
        inv = self._make_inventory()
        self.assertEqual(len(list(inv)), 3)

    def test_summary_format(self):
        inv = self._make_inventory()
        s = inv.summary()
        self.assertIn("module", s.lower())
        self.assertIn("function", s.lower())
        self.assertIn("variable", s.lower())

    def test_to_dict_keys(self):
        inv = self._make_inventory()
        d = inv.to_dict()
        self.assertIn("session_timestamp", d)
        self.assertIn("total_symbols", d)
        self.assertIn("symbols", d)
        self.assertEqual(d["total_functions"], 2)
        self.assertEqual(d["total_variables"], 1)

    def test_empty_inventory(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import SymbolInventory
        inv = SymbolInventory()
        self.assertEqual(len(inv), 0)
        self.assertEqual(inv.modules, [])


# ---------------------------------------------------------------------------
# _classify_kind
# ---------------------------------------------------------------------------

class TestClassifyKind(unittest.TestCase):

    def setUp(self):
        from GM_VIP_Automation_Framework.core import symbol_discovery as sd
        self.classify = sd._classify_kind
        self.SymbolKind = sd.SymbolKind

    def test_code_column(self):
        self.assertEqual(self.classify("foo", "CODE"), self.SymbolKind.FUNCTION)

    def test_proc_column(self):
        self.assertEqual(self.classify("foo", "PROC"), self.SymbolKind.FUNCTION)

    def test_data_column(self):
        self.assertEqual(self.classify("foo", "DATA"), self.SymbolKind.VARIABLE)

    def test_bss_column(self):
        self.assertEqual(self.classify("foo", "BSS"), self.SymbolKind.VARIABLE)

    def test_g_prefix_heuristic(self):
        self.assertEqual(self.classify("g_myVar", ""), self.SymbolKind.VARIABLE)

    def test_s_prefix_heuristic(self):
        self.assertEqual(self.classify("s_count", ""), self.SymbolKind.VARIABLE)

    def test_allcaps_heuristic(self):
        self.assertEqual(self.classify("MY_GLOBAL", ""), self.SymbolKind.VARIABLE)

    def test_default_function(self):
        self.assertEqual(self.classify("myFunc", ""), self.SymbolKind.FUNCTION)


# ---------------------------------------------------------------------------
# discover_symbols (integration over mock conn)
# ---------------------------------------------------------------------------

class TestDiscoverSymbols(unittest.TestCase):

    def test_returns_inventory(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import (
            discover_symbols, SymbolInventory,
        )
        conn = _make_conn()
        inv = discover_symbols(pattern="*", connection=conn, resolve_addresses=False)
        self.assertIsInstance(inv, SymbolInventory)

    def test_discovers_functions(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import discover_symbols
        conn = _make_conn()
        inv = discover_symbols(connection=conn, resolve_addresses=False)
        self.assertGreater(len(inv.functions), 0)

    def test_discovers_variables(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import discover_symbols
        conn = _make_conn()
        inv = discover_symbols(connection=conn, resolve_addresses=False)
        self.assertGreater(len(inv.variables), 0)

    def test_modules_extracted(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import discover_symbols
        conn = _make_conn()
        inv = discover_symbols(connection=conn, resolve_addresses=False)
        mods = inv.modules
        self.assertTrue(any("main.c" in m for m in mods))

    def test_resolve_addresses_calls_symbol_exist(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import discover_symbols
        conn = _make_conn()
        discover_symbols(connection=conn, resolve_addresses=True, max_symbols=5)
        calls_str = [str(c) for c in conn.fnc.call_args_list]
        self.assertTrue(any("SYMBOL.EXIST" in c for c in calls_str))

    def test_empty_area_returns_empty_inventory(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import discover_symbols
        conn = _make_conn(area_text="")
        inv = discover_symbols(connection=conn, resolve_addresses=False)
        self.assertEqual(len(inv), 0)

    def test_discover_modules_helper(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import discover_modules
        conn = _make_conn()
        mods = discover_modules(connection=conn)
        self.assertIsInstance(mods, list)
        self.assertTrue(any("main.c" in m for m in mods))

    def test_discover_functions_helper(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import (
            discover_functions, SymbolKind,
        )
        conn = _make_conn()
        funcs = discover_functions(connection=conn)
        self.assertTrue(all(f.kind == SymbolKind.FUNCTION for f in funcs))

    def test_discover_variables_helper(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import (
            discover_variables, SymbolKind,
        )
        conn = _make_conn()
        varis = discover_variables(connection=conn)
        self.assertTrue(all(v.kind == SymbolKind.VARIABLE for v in varis))

    def test_cmd_area_clear_issued(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import discover_symbols
        conn = _make_conn()
        discover_symbols(connection=conn, resolve_addresses=False)
        cmd_calls = [str(c) for c in conn.cmd.call_args_list]
        self.assertTrue(any("AREA.CLEAR" in c for c in cmd_calls))

    def test_cmd_symbol_list_issued(self):
        from GM_VIP_Automation_Framework.core.symbol_discovery import discover_symbols
        conn = _make_conn()
        discover_symbols(connection=conn, resolve_addresses=False)
        cmd_calls = [str(c) for c in conn.cmd.call_args_list]
        self.assertTrue(any("SYMBOL.LIST" in c for c in cmd_calls))


# ---------------------------------------------------------------------------
# Public exports from the package
# ---------------------------------------------------------------------------

class TestPublicExports(unittest.TestCase):

    def test_top_level_imports(self):
        import GM_VIP_Automation_Framework as fw
        self.assertTrue(hasattr(fw, "discover_symbols"))
        self.assertTrue(hasattr(fw, "discover_modules"))
        self.assertTrue(hasattr(fw, "discover_functions"))
        self.assertTrue(hasattr(fw, "discover_variables"))
        self.assertTrue(hasattr(fw, "SymbolInventory"))
        self.assertTrue(hasattr(fw, "DiscoveredSymbol"))
        self.assertTrue(hasattr(fw, "SymbolKind"))

    def test_core_exports(self):
        from GM_VIP_Automation_Framework import core
        self.assertTrue(hasattr(core, "discover_symbols"))
        self.assertTrue(hasattr(core, "SymbolInventory"))


if __name__ == "__main__":
    unittest.main()
